#ifndef  INT24_TYPES_VERSION
#define  INT24_TYPES_VERSION _24Bit_Sample_Types_
#define  INT24_TYPES_VERSION_NUMBER INT24_TYPES_VERSION
#define  INT24_TYPES_VERSION_STRING L"0.0.0.3"
#define  SET_NAMESPACE stepflow
#endif
