/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      UInt24Type.cpp                             ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/

//////////////////////////////////////////////////////////
// IConvertible interface implementation for UInt24Type //
//////////////////////////////////////////////////////////

#include <settings.h>
#include <WaveLib.inl/half.hpp>
#include "int24bittypes.hpp"
#include "UInt24Type.hpp"


bool Stepflow::UInt24::ToBoolean( System::IFormatProvider^ provider )
{
	return UInt24::operator unsigned int(*this) > 0;
}

unsigned char Stepflow::UInt24::ToByte(System::IFormatProvider^ provider)
{
	return static_cast<byte>( UInt24::operator unsigned int(*this) );
}

wchar_t Stepflow::UInt24::ToChar(System::IFormatProvider^ provider)
{
	return  static_cast<wchar_t>( UInt24::operator unsigned int(*this) );
}

System::DateTime Stepflow::UInt24::ToDateTime(System::IFormatProvider^ provider)
{
	return System::DateTime( UInt24::operator unsigned int(*this) );
}

System::Decimal Stepflow::UInt24::ToDecimal( System::IFormatProvider^ provider )
{
	return System::Decimal( UInt24::operator unsigned int(*this) );
}

double Stepflow::UInt24::ToDouble(System::IFormatProvider^ provider)
{
	return  (double)UInt24::operator unsigned int(*this);
}

short Stepflow::UInt24::ToInt16(System::IFormatProvider^ provider)
{
	return static_cast<short>(UInt24::operator unsigned int(*this));
}

int Stepflow::UInt24::ToInt32(System::IFormatProvider^ provider)
{
	return static_cast<int>(UInt24::operator unsigned int(*this));
}

long long Stepflow::UInt24::ToInt64(System::IFormatProvider^ provider)
{
	return  (long long)UInt24::operator unsigned int(*this);
}

System::SByte Stepflow::UInt24::ToSByte(System::IFormatProvider^ provider)
{
	return static_cast<System::SByte>(UInt24::operator unsigned int(*this));
}

float Stepflow::UInt24::ToSingle(System::IFormatProvider^ provider)
{
	return static_cast<float>(UInt24::operator unsigned int(*this));
}

System::String^ Stepflow::UInt24::ToString(System::IFormatProvider^ provider)
{
	return UInt24::operator unsigned int(*this).ToString();
}

System::Object^ Stepflow::UInt24::ToType(System::Type^ conversionType, System::IFormatProvider^ provider)
{
	return System::Convert::ChangeType( UInt24::operator uint(*this), conversionType, provider );
}

unsigned short Stepflow::UInt24::ToUInt16(System::IFormatProvider^ provider)
{
	return static_cast<word>(UInt24::operator unsigned int(*this));
}

unsigned int Stepflow::UInt24::ToUInt32(System::IFormatProvider^ provider)
{
	return UInt24::operator unsigned int(*this);
}

unsigned long long Stepflow::UInt24::ToUInt64(System::IFormatProvider^ provider)
{
	return UInt24::operator unsigned int(*this);
}
